export const recipeData = [
  {
    _id: 1,
    name: "Candied Yams",
    link: "img",
    ingredients: [
      "3 large sweet potatoes, peeled and cubed",
      "1/2 cup packed brown sugar",
      "1/4 cup butter, melted",
      "1/4 cup orange juice",
      "1 teaspoon ground cinnamon",
      "1/2 teaspoon ground nutmeg",
      "1/4 teaspoon ground cloves",
      "marshmallows (optional)",
    ],
    instructions: [
      "Boil the Sweet Potatoes",
      "Prepare the Sauce",
      "Bring to Boil and Simmer for 5min",
      "Pour Sauce over Potatoes and Toss",
      "Put in Baking Dish",
      "Bake at 350F for 20-25min",
    ],
    tips: [
      "For a richer flavor, use a combination of light and dark brown sugar",
      "For extra flavor, add a splash of vanilla extract or bourbon to the sauce",
      "For a crispy topping, broil the dish for a couple minutes after baking, WATCH CLOSELY",
    ],
  },
  {
    _id: 2,
    name: "Macaroni and Cheese",
    link: "img",
    ingredients: "",
    instructions: "",
    tips: "",
  },
  {
    _id: 3,
    name: "Cornbread",
    link: "img",
    ingredients: "",
    instructions: "",
    tips: "",
  },
  {
    _id: 4,
    name: "Cranberry Sauce",
    link: "img",
    ingredients: "",
    instructions: "",
    tips: "",
  },
  {
    _id: 5,
    name: "Peach Cobbler",
    link: "img",
    ingredients: "",
    instructions: "",
    tips: "",
  },
  {
    _id: 6,
    name: "Sweet Potato Pie",
    link: "img",
    ingredients: "",
    instructions: "",
    tips: "",
  },
  {
    _id: 7,
    name: "Collard Greens",
    link: "img",
    ingredients: "",
    instructions: "",
    tips: "",
  },
  {
    _id: 8,
    name: "Stuffing/Dressing",
    link: "img",
    ingredients: "",
    instructions: "",
    tips: "",
  },
  {
    _id: 9,
    name: "Mashed Potatoes and Gravy",
    link: "img",
    ingredients: "",
    instructions: "",
    tips: "",
  },
  {
    _id: 10,
    name: "Potato Salad",
    link: "img",
    ingredients: "",
    instructions: "",
    tips: "",
  },
];
