export const recipeData = [
  {
    _id: 1,
    name: "Candied Yams",
    link: "img",
    ingredients: [
      "3 large sweet potatoes, peeled and cubed",
      "1/2 cup packed brown sugar",
      "1/4 cup butter, melted",
      "1/4 cup orange juice",
      "1 teaspoon ground cinnamon",
      "1/2 teaspoon ground nutmeg",
      "1/4 teaspoon ground cloves",
      "marshmallows (optional)",
    ],
    instructions: [
      "Boil the Sweet Potatoes",
      "Prepare the Sauce",
      "Bring to Boil and Simmer for 5min",
      "Pour Sauce over Potatoes and Toss",
      "Put in Baking Dish",
      "Bake at 350F for 20-25min",
    ],
    tips: [
      "For a richer flavor, use a combination of light and dark brown sugar",
      "For extra flavor, add a splash of vanilla extract or bourbon to the sauce",
      "For a crispy topping, broil the dish for a couple minutes after baking, WATCH CLOSELY",
    ],
  },
  {
    _id: 2,
    name: "Macaroni and Cheese",
    link: "img",
    ingredients: [
      "1 pound elbow macaroni",
      "1/2 cup unsalted butter",
      "1/2 cup all-purpose flour",
      "4 cups whole milk",
      "1 teaspoon salt",
      "1/2 teaspoon black pepper",
      "4 cups shredded sharp cheddar cheese",
      "1 cup shredded Gruyère cheese",
      "1/2 cup breadcrumbs",
      "2 tablespoons butter, melted",
    ],
    instructions: [
      "Cook the Pasta",
      "Melt the Butter on Med",
      "Whisk in Flour for 1min, until Bubbly and Golden",
      "Whisk in Milk, Salt, and Pepper, STIR CONSTANTLY",
      "WHEN SAUCE THICKENS, Remove from heat and Stir in Gruyère cheese",
      "Combine Pasta and Cheese sauce",
      "Add to Greased Bake Dish and Bake at 350F for 20-25min",
    ],
    tips: [
      "To prevent mushiness, cook the pasta al dente",
      "DONT OVERBAKE! Bake until bubbly and golden brown",
      "SERVE HOT!",
    ],
  },
  {
    _id: 3,
    name: "Cornbread",
    link: "img",
    ingredients: [
      "1 cup yellow cornmeal",
      "1 cup all-purpose flour",
      "1 tablespoon baking powder",
      "1 teaspoon salt",
      "1/4 cup granulated sugar",
      "1 large egg, beaten",
      "1 1/4 cups buttermilk",
      "3 tablespoons unsalted butter, melted",
    ],
    instructions: [
      "Preheat oven to 425F",
      "Combine Dry Ingredients",
      "Combine Wet ingredients, in seperate bowl",
      "Mix wet and dry Ingredients",
      "Stir in Melted Butter",
      "Pour in Greased 8in Cast Iron Skillet and Bake for 20-25min",
    ],
    tips: [
      "For softer crust, use 9x9 baking pan",
      "For a more moist cornbread, use buttermilk",
      "For sweeter flavor, add honey, molasses, or maple syrup",
    ],
  },
  {
    _id: 4,
    name: "Cranberry Sauce",
    link: "img",
    ingredients: [
      "12 ounces fresh cranberries",
      "1 cup granulated sugar",
      "1/2 cup water",
      "1 orange, zested and juiced",
    ],
    instructions: [
      "Combine Ingredients in Medium Saucepan",
      "Bring to Boil over med-high heat",
      "Simmer for 10-15min",
      "Cool then Serve",
    ],
    tips: [
      "For sweeter sauce, add more sugar",
      "For tangier sauce, reduce the amount of sugar and add a splash of lemon juice",
      "For a festive twist, add a cinnomon stick or cloves to the pot while simmering",
      "For unique flavor, add a splash of bourbon or brandy",
      "For smoother texture, use a blender to puree the sauce",
    ],
  },
  {
    _id: 5,
    name: "Peach Cobbler",
    link: "img",
    ingredients: [
      "6 cups fresh peaches, peeled, pitted, and sliced",
      "1/2 cup granulated sugar",
      "1 tablespoon cornstarch",
      "1 teaspoon ground cinnamon",
      "1/4 teaspoon ground nutmeg",
      "2 cups all-purpose flour",
      "3 teaspoons baking powder",
      "1/2 teaspoon salt",
      "1/4 cup unsalted butter, cut into small cubes",
      "1/2 cup buttermilk",
    ],
    instructions: [
      "Prepare Filling by combining Peaches, Sugar, Cornstarch, Cinnamon, and Nutmeg in a large bowl, SET ASIDE",
      "Whisk together Flour, Baking Powder, and Salt, in a large bowl",
      "Cut in Butter, until crumbly",
      "Stir in Buttermilk",
      "Preheat Oven at 375F",
      "Pour Filling into 9x13in baking dish",
      "Drop spoonfuls of Biscuit Dough over Filling, SPACE EVENLY",
      "Bake for 30-35min",
    ],
    tips: [
      "For richer flavor, add a tbsp of butter to filling",
      "For quicker cobbler, use a pre-made biscuit dough",
      "For using frozen peaches, thaw completely before using",
    ],
  },
  {
    _id: 6,
    name: "Sweet Potato Pie",
    link: "img",
    ingredients: "",
    instructions: "",
    tips: "",
  },
  {
    _id: 7,
    name: "Collard Greens",
    link: "img",
    ingredients: "",
    instructions: "",
    tips: "",
  },
  {
    _id: 8,
    name: "Stuffing/Dressing",
    link: "img",
    ingredients: "",
    instructions: "",
    tips: "",
  },
  {
    _id: 9,
    name: "Mashed Potatoes and Gravy",
    link: "img",
    ingredients: "",
    instructions: "",
    tips: "",
  },
  {
    _id: 10,
    name: "Potato Salad",
    link: "img",
    ingredients: "",
    instructions: "",
    tips: "",
  },
];
