import Cranberry from "../assets/images/CSauce.jpeg";
import PeachCobbler from "../assets/images/Cobbler.jpeg";
import MacAndCheese from "../assets/images/MacNCheese.jpeg";
import SweetPotatoPie from "../assets/images/SweetPPie.jpeg";
import Yams from "../assets/images/CandiedYams.jpeg";
import Cornbread from "../assets/images/Cornbread.jpeg";
import Collards from "../assets/images/Collards.jpeg";
import Potatoes from "../assets/images/MashPandGravy.jpeg";
import PotatoSalad from "../assets/images/PotatoSalad.webp";
import Stuffing from "../assets/images/Stuffing.jpeg";

export const recipeData = [
  {
    _id: 1,
    name: "Candied Yams",
    link: Yams,
    ingredients: [
      "3 large sweet potatoes, peeled and cubed",
      "1/2 cup packed brown sugar",
      "1/4 cup butter, melted",
      "1/4 cup orange juice",
      "1 teaspoon ground cinnamon",
      "1/2 teaspoon ground nutmeg",
      "1/4 teaspoon ground cloves",
      "marshmallows (optional)",
    ],
    instructions: [
      "Boil the Sweet Potatoes",
      "Prepare the Sauce",
      "Bring to Boil and Simmer for 5min",
      "Pour Sauce over Potatoes and Toss",
      "Put in Baking Dish",
      "Bake at 350F for 20-25min",
    ],
    tips: [
      "For a richer flavor, use a combination of light and dark brown sugar",
      "For extra flavor, add a splash of vanilla extract or bourbon to the sauce",
      "For a crispy topping, broil the dish for a couple minutes after baking, WATCH CLOSELY",
    ],
  },
  {
    _id: 2,
    name: "Macaroni and Cheese",
    link: MacAndCheese,
    ingredients: [
      "1 pound elbow macaroni",
      "1/2 cup unsalted butter",
      "1/2 cup all-purpose flour",
      "4 cups whole milk",
      "1 teaspoon salt",
      "1/2 teaspoon black pepper",
      "4 cups shredded sharp cheddar cheese",
      "1 cup shredded Gruyère cheese",
      "1/2 cup breadcrumbs",
      "2 tablespoons butter, melted",
    ],
    instructions: [
      "Cook the Pasta",
      "Melt the Butter on Med",
      "Whisk in Flour for 1min, until Bubbly and Golden",
      "Whisk in Milk, Salt, and Pepper, STIR CONSTANTLY",
      "WHEN SAUCE THICKENS, Remove from heat and Stir in Gruyère cheese",
      "Combine Pasta and Cheese sauce",
      "Add to Greased Bake Dish and Bake at 350F for 20-25min",
    ],
    tips: [
      "To prevent mushiness, cook the pasta al dente",
      "DONT OVERBAKE! Bake until bubbly and golden brown",
      "SERVE HOT!",
    ],
  },
  {
    _id: 3,
    name: "Cornbread",
    link: Cornbread,
    ingredients: [
      "1 cup yellow cornmeal",
      "1 cup all-purpose flour",
      "1 tablespoon baking powder",
      "1 teaspoon salt",
      "1/4 cup granulated sugar",
      "1 large egg, beaten",
      "1 1/4 cups buttermilk",
      "3 tablespoons unsalted butter, melted",
    ],
    instructions: [
      "Preheat oven to 425F",
      "Combine Dry Ingredients",
      "Combine Wet ingredients, in seperate bowl",
      "Mix wet and dry Ingredients",
      "Stir in Melted Butter",
      "Pour in Greased 8in Cast Iron Skillet and Bake for 20-25min",
    ],
    tips: [
      "For softer crust, use 9x9 baking pan",
      "For a more moist cornbread, use buttermilk",
      "For sweeter flavor, add honey, molasses, or maple syrup",
    ],
  },
  {
    _id: 4,
    name: "Cranberry Sauce",
    link: Cranberry,
    ingredients: [
      "12 ounces fresh cranberries",
      "1 cup granulated sugar",
      "1/2 cup water",
      "1 orange, zested and juiced",
    ],
    instructions: [
      "Combine Ingredients in Medium Saucepan",
      "Bring to Boil over med-high heat",
      "Simmer for 10-15min",
      "Cool then Serve",
    ],
    tips: [
      "For sweeter sauce, add more sugar",
      "For tangier sauce, reduce the amount of sugar and add a splash of lemon juice",
      "For a festive twist, add a cinnomon stick or cloves to the pot while simmering",
      "For unique flavor, add a splash of bourbon or brandy",
      "For smoother texture, use a blender to puree the sauce",
    ],
  },
  {
    _id: 5,
    name: "Peach Cobbler",
    link: PeachCobbler,
    ingredients: [
      "6 cups fresh peaches, peeled, pitted, and sliced",
      "1/2 cup granulated sugar",
      "1 tablespoon cornstarch",
      "1 teaspoon ground cinnamon",
      "1/4 teaspoon ground nutmeg",
      "2 cups all-purpose flour",
      "3 teaspoons baking powder",
      "1/2 teaspoon salt",
      "1/4 cup unsalted butter, cut into small cubes",
      "1/2 cup buttermilk",
    ],
    instructions: [
      "Prepare Filling by combining Peaches, Sugar, Cornstarch, Cinnamon, and Nutmeg in a large bowl, SET ASIDE",
      "Whisk together Flour, Baking Powder, and Salt, in a large bowl",
      "Cut in Butter, until crumbly",
      "Stir in Buttermilk",
      "Preheat Oven at 375F",
      "Pour Filling into 9x13in baking dish",
      "Drop spoonfuls of Biscuit Dough over Filling, SPACE EVENLY",
      "Bake for 30-35min",
    ],
    tips: [
      "For richer flavor, add a tbsp of butter to filling",
      "For quicker cobbler, use a pre-made biscuit dough",
      "For using frozen peaches, thaw completely before using",
    ],
  },
  {
    _id: 6,
    name: "Sweet Potato Pie",
    link: SweetPotatoPie,
    ingredients: [
      "3 large sweet potatoes, peeled and cubed",
      "1 cup granulated sugar",
      "1/2 cup packed light brown sugar",
      "1/2 cup unsalted butter, melted",
      "3 large eggs, beaten",
      "1 teaspoon vanilla extract",
      "1/2 teaspoon ground cinnamon",
      "1/4 teaspoon ground ginger",
      "1/4 teaspoon ground cloves",
      "1/4 teaspoon salt",
      "1 1/2 cups all-purpose flour",
      "1/2 teaspoon salt",
      "1/2 cup (1 stick) unsalted butter, cold and cubed",
      "1/4 cup ice water",
    ],
    instructions: [
      "Boil Sweet Potatoes, until tender",
      "Drain and Mash thoroughly",
      "Combine Sweet Potatoes, Granulated Sugar, Brown Sugar, Melted Butter, Eggs, Vanilla, Cinnamon, Ginger, Cloves, and Salt. Mix well",
      "Combine Flour and Salt for the crust",
      "Cut in Cold Butter, until crumbly",
      "Gradually add Ice Water, tossing with a fork until dough comes together",
      "Divide Dough into two discs, Wrap, and Refrigerate for 30 min",
      "Roll out one disc of Dough to fit a 9-inch pie plate.",
      "Transfer Crust to Pie Plate, pressing into bottom and sides",
      "Pour Sweet Potato Filling into Crust",
      "Roll out second disc of Dough",
      "Cut Dough into Strips",
      "Weave Strips over Filling",
      "Trim and crimp edges",
      "Bake at 350F for 45-50 min",
    ],
    tips: [
      "For richer flavor, use a combination of light and dark brown sugar.",
      "To ensure a flaky crust, keep the butter cold and work quickly when incorporating it into the flour.",
      "For sweeter filling, add a tbsp of maple syrup or honey.",
      "To prevent the crust from becoming too brown, cover the edges with foil during the last 15 min of baking.",
    ],
  },
  {
    _id: 7,
    name: "Collard Greens",
    link: Collards,
    ingredients: [
      "1 bunch collard greens, trimmed and chopped",
      "1 smoked turkey neck",
      "1 onion, chopped",
      "2 cloves garlic, minced",
      "1 teaspoon red pepper flakes",
      "1 tablespoon apple cider vinegar",
      "Salt and pepper to taste",
    ],
    instructions: [
      "Combine Collard Greens, Smoked Turkey Neck, Onion, Garlic, and Red Pepper Flakes in a large pot",
      "Add enough Water to Cover the Greens",
      "Bring to Boil",
      "Reduce Heat to low, Simmer, Covered, for 2-3 hours",
      "Remove the Turkey Neck from pot and discard",
      "Stir in Apple Cider Vinegar, Salt, and Pepper",
      "Simmer for 10-15 min",
    ],
    tips: [
      "For a richer flavor, add a splash of hot sauce or a drizzle of honey",
      "To tender greens, cook them longer or use a pressure cooker",
      "For smoky flavor, use a smoked turkey neck ",
      "Serve Hot",
    ],
  },
  {
    _id: 8,
    name: "Stuffing/Dressing",
    link: Stuffing,
    ingredients: [
      "1 loaf stale white bread, cubed",
      "1/2 cup butter, melted",
      "1 onion, chopped",
      "2 celery stalks, chopped",
      "1/2 cup chopped parsley",
      "1 teaspoon dried sage",
      "1/2 teaspoon dried thyme",
      "1/4 teaspoon black pepper",
      "1/2 teaspoon salt",
      "4 cups chicken broth",
      "2 eggs, beaten",
    ],
    instructions: [
      "Preheat oven to 350F",
      "Combine Bread cubes, Melted Butter, Onion, Celery, Parsley, Sage, Thyme, Pepper, and Salt",
      "Gradually Add Chicken Broth to Bread Mixture, Stir until moistened",
      "Stir in Beaten Eggs",
      "Transfer Stuffing Mixture to Greased Baking Dish",
      "Bake for 30-40 min",
    ],
    tips: [
      "For richer flavor, add sausage, bacon, or oysters to the stuffing",
      "For  moist stuffing, add more chicken broth",
      "For crispy top, sprinkle the stuffing with breadcrumbs before baking",
    ],
  },
  {
    _id: 9,
    name: "Mashed Potatoes and Gravy",
    link: Potatoes,
    ingredients: [
      "3 pounds russet potatoes, peeled and cubed",
      "1/2 cup unsalted butter",
      "1/2 cup milk",
      "1/4 cup heavy cream",
      "1 teaspoon salt",
      "1/4 teaspoon black pepper",
      "1/4 cup all-purpose flour",
      "1/4 cup butter",
      "2 cups chicken or turkey broth",
    ],
    instructions: [
      "Boil Potatoes in a large pot of salted water until tender",
      "Drain Potatoes and Return to Pot",
      "Mash Potatoes with Potato Masher",
      "Add butter, Milk, Cream, Salt, and Pepper to Mashed Potatoes",
      "Mash until smooth and creamy",
      "To start gravy, Melt Butter in saucepan over medium heat",
      "Whisk in Flour and Cook for 1 min, or until bubbly",
      "Gradually Whisk in Broth, Stir constantly until smooth and thickened",
      "Season with Salt and Pepper",
    ],
    tips: [
      "For extra creamy mashed potatoes, add a little bit of sour cream",
      "For richer flavor, use half butter and half olive oil",
      "To keep mashed potatoes warm, place them in a slow cooker on low heat.",
      "For the most flavorful gravy, use the drippings from your roasted turkey or chicken",
      "Be careful not to burn the flour",
      "Strain gravy before serving",
    ],
  },
  {
    _id: 10,
    name: "Potato Salad",
    link: PotatoSalad,
    ingredients: [
      "5 pounds red potatoes, scrubbed and quartered",
      "1/2 cup mayonnaise",
      "1/4 cup sour cream",
      "2 tablespoons white vinegar",
      "1 teaspoon Dijon mustard",
      "1/2 teaspoon salt",
      "1/4 teaspoon black pepper",
      "1/4 cup finely chopped onion",
      "2 tablespoons finely chopped fresh dill",
    ],
    instructions: [
      "Boil Potatoes in a large pot of salted water until tender",
      "Drain Potatoes and let cool slightly",
      "Combine Mayonnaise, Sour Cream, Vinegar, Mustard, Salt, and Pepper, in large bowl",
      "Add Potatoes, Onion, and Dill",
      "Chill for at least 1 hr",
    ],
    tips: [
      "For a creamier potato salad, use more mayonnaise and sour cream.",
      "For a tangier potato salad, add more vinegar and mustard.",
      "For a heartier potato salad, add bacon, ham, or hard-boiled eggs.",
      "To add a touch of sweetness, add a teaspoon of sugar to the dressing.",
    ],
  },
];
